language: python
dist: trusty
cache:
  pip: true
#  directories:
#    - $HOME/.cache/samples
python:
  - "3.6"
install:
  - git clone -b merge_master --recursive https://github.com/rednaga/yara-python-1 yara-python
  - cd yara-python
  - CFLAGS="-std=gnu99" python setup.py build --enable-dex install
  - cd ../
  - pip install --upgrade pip
  - pip install -e .[dev,test]
script:
  - ./prep-release.py | true
  - python -m pytest -s
